# Generated by Django 4.2.7 on 2026-03-25 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wattage',
            field=models.CharField(blank=True, choices=[('0W', '0W'), ('100W', '100W'), ('200W', '200W'), ('250W', '250W'), ('300W', '300W'), ('350W', '350W'), ('400W', '400W'), ('500W', '500W'), ('550W', '550W'), ('1KW', '1KW'), ('1.5KW', '1.5KW'), ('2KW', '2KW'), ('3KW', '3KW'), ('5KW', '5KW'), ('10KW', '10KW')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
