services:
  - type: web
    name: mahi-solar-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: mahi-solar-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: mahi-solar-db
    plan: free
